[lint]
output-format = "concise"
respect-ignore = true
respect-gitignore = true
rules = [
  "MD001",
  "MD002",
  "MD003",
  "MD004",
  "MD005",
  "MD006",
  "MD009",
  "MD010",
  "MD012",
  "MD013",
  "MD014",
  "MD018",
  "MD019",
  "MD020",
  "MD021",
  "MD022",
  "MD023",
  "MD024",
  "MD025",
  "MD026",
  "MD027",
  "MD028",
  "MD029",
  "MD030",
  "MD031",
  "MD032",
  "MD033",
  "MD034",
  "MD035",
  "MD036",
  "MD037",
  "MD038",
  "MD039",
  "MD040",
  "MD041",
  "MD046",
  "MD047",
]

[lint.md013]
line-length = 120

[lint.md024]
allow-different-nesting = true
