[package]
name = "akioi-2048"
version = "0.4.2"
description = "A 2048 engine with multiplier tiles"
edition = "2024"
license = "MIT"
readme = "README.md"

[lib]
crate-type = ["rlib"]

[dependencies]
rand = "0.9.2"
