[package]
name = "akioi_2048"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"] # 生成 Python 扩展

[dependencies]
rand = "0.8"
pyo3 = { version = "0.21", features = ["extension-module"] }
