# ruff.toml — 全规则 + 预览 + 激进修复
target-version = "py313"
fix = true
unsafe-fixes = true

[per-file-ignores]
"tests/**" = ["S101","PLR2004"]
"scripts/**" = ["T201"]



[lint]
# 全开
select = ["ALL"]
# 你要狠，那就 extend-select 也给 ALL（功能上等价于上面这行）
extend-select = ["ALL"]
preview = true

# isort（Ruff 内置）最严倾向配置
[lint.isort]
combine-as-imports = true
force-wrap-aliases = true
force-single-line = true
force-sort-within-sections = true
from-first = true
lines-after-imports = 1
lines-between-types = 1
order-by-type = true
relative-imports-order = "closest-to-furthest"
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
known-first-party = ["src"]

[lint.pydocstyle]
convention = "google"
