name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv and maturin
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          pip install maturin
      - name: Ruff check
        run: |
          uv run ruff check .
      - name: Cargo check
        run: |
          cargo clippy
      - name: Mado check
        uses: akiomik/mado@v0.3.0
      - name: Build extension
        run: |
          uv run maturin develop
      - name: Run tests
        run: |
          uv run pytest
