name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v6
      - name: Ruff check
        uses: astral-sh/ruff-action@v3
      - name: Mado check
        uses: akiomik/mado@v0.3.0
      - name: Run tests
        run: |
          uv run pytest   
      - name: Cargo clippy
        run: |
          cargo clippy
