name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-13, macos-14, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv and maturin
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          pip install maturin
      - name: Build extension
        run: |
          uv run --python ${{ matrix.python-version }} maturin develop --release
      - name: Run tests
        run: |
          uv run --python ${{ matrix.python-version }} pytest
