name: Publish to PyPI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: PyO3/maturin-action@v1
        with:
          command: publish
          args: --no-sdist --manylinux 2014 -u __token__ -p ${{ secrets.PYPI_API_TOKEN }}
          maturin-version: latest
        env:
          MATURIN_PYPI_NAME: akioi-2048
