name: Release

on:
  push:
    tags: ['v*']

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12", "3.13"]
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
          - os: ubuntu-latest
            target: aarch64-unknown-linux-gnu
          - os: macos-13
            target: x86_64-apple-darwin
          - os: macos-14
            target: aarch64-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv and maturin
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          pip install maturin
      - name: Build wheels
        run: |
          uv run --python ${{ matrix.python-version }} maturin build --release --target ${{ matrix.target }} --out dist
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.target }}-py${{ matrix.python-version }}
          path: dist/*.whl

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: wheels-*
          merge-multiple: true
      - name: Publish to PyPI
        run: |
          pip install maturin
          maturin upload --skip-existing dist/*
        env:
          MATURIN_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
          MATURIN_USERNAME: __token__
